In [1]:
import numpy as np

array函数，两种构建方法

In [ ]:
example1=np.zeros((2,3))
print(example1)
example2=np.ones((2,3))
print(example2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


输出ndarray对象的四个属性：大小，形状，数据类型，维度

In [35]:
example3=np.array([[1,2,4],[2,5,8]])
print(example3.size)
print(example3.shape)
print(example3.dtype)
print(example3.ndim)

6
(2, 3)
int64
2


改变形状,reshape()函数

In [36]:
print(np.reshape(example3,(-1)))

[1 2 4 2 5 8]


ndarray的算数操作

In [41]:
example4=np.array([[11,22,3,4],[2,33,4,35]])
example5=np.array([[31,4,52,6],[32,9,73,6]])
print(example4<example5)
print(example4+example5)
print(example4*example5)
print(example4/example5)
print(example4**example5)  
print(example4.max())
print(example4.min())
print(example4.sum())
print(example4.max(axis=0))
print(example4.argmax(axis=0))
print(example4.max(axis=1))
print(example4.argmax(axis=1))


[[ True False  True  True]
 [ True False  True False]]
[[42 26 55 10]
 [34 42 77 41]]
[[341  88 156  24]
 [ 64 297 292 210]]
[[0.35483871 5.5        0.05769231 0.66666667]
 [0.0625     3.66666667 0.05479452 5.83333333]]
[[1349464372445695011              234256 -903054539411881455
                 4096]
 [         4294967296      46411484401953                   0
           1838265625]]
35
2
114
[11 33  4 35]
[0 1 1 1]
[22 35]
[1 3]


随机数生成

In [45]:
print(np.random.random_sample(size=[1,2]))
print(np.random.choice(a=[1,2,3,4],size=3,replace=False))
print(np.random.randint(1,10,size=(2)))

[[0.71595186 0.00799128]]
[1 4 2]
[7 6]
