导入numpy库

In [2]:
import numpy as np

In [4]:
a=[1,2,3,4,5,6,7,8]
a=np.reshape(a,(2,4))
print(a)

[[1 2 3 4]
 [5 6 7 8]]


输出实例对象属性

In [5]:
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)

(2, 4)
int64
2
8


矩阵运算

In [ ]:
x1=np.array([[1,2],[3,4]])
x2=np.array([[5,6],[7,8]])
sum=x1+x2
sub=x1-x2
mul=x1*x2
div=x1/x2
log=x1>x2
print(sum)
print(sub)
print(mul)
print(div)
print(log)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[False False]
 [False False]]


简单统计

In [8]:
x3=np.array([11,22,33,4,55,66])
print(np.sum(x3))
print(np.mean(x3))
print(np.max(x3))
print(np.min(x3))
print(np.argmax(x3))
print(np.argmin(x3))


191
31.833333333333332
66
4
5
3


二维统计